// AUTO-GENERATED by scripts/sync-albums.mjs
// Do not edit by hand. Re-run the script to refresh from Spotify.

export type Album = {
  slug: string;
  title: string;
  year: number;
  coverUrl: string;
  spotifyUrl?: string | null;
  appleUrl?: string | null;
  youtubeUrl?: string | null;
  bandcampUrl?: string | null;
};

export const albums: Album[] = [
  {
    "slug": "who-are-we",
    "title": "Who Are We?",
    "year": 2025,
    "coverUrl": "https://i.scdn.co/image/ab67616d0000b273bfac377504051c04b1f48867",
    "spotifyUrl": "https://open.spotify.com/album/4kRCJutBZ6ycQgTsFeswuQ",
    "appleUrl": null,
    "youtubeUrl": null,
    "bandcampUrl": null
  },
  {
    "slug": "waiting",
    "title": "Waiting",
    "year": 2024,
    "coverUrl": "https://i.scdn.co/image/ab67616d0000b273060c79f917829821b8e9f1ba",
    "spotifyUrl": "https://open.spotify.com/album/0jswt2MgrYoPHrxnk7bQmo",
    "appleUrl": null,
    "youtubeUrl": null,
    "bandcampUrl": null
  },
  {
    "slug": "two-sides-of-the-same-coin",
    "title": "Two Sides of the Same Coin",
    "year": 2024,
    "coverUrl": "https://i.scdn.co/image/ab67616d0000b2731b4c0fedef20f99f13ca8464",
    "spotifyUrl": "https://open.spotify.com/album/515q4iCM7oRPGKBQXGoaOG",
    "appleUrl": null,
    "youtubeUrl": null,
    "bandcampUrl": null
  },
  {
    "slug": "inner-voice",
    "title": "Inner Voice",
    "year": 2023,
    "coverUrl": "https://i.scdn.co/image/ab67616d0000b273e93e04b16f984f0282655b36",
    "spotifyUrl": "https://open.spotify.com/album/5u7BT343SoPWdJM1I5NdBY",
    "appleUrl": null,
    "youtubeUrl": null,
    "bandcampUrl": null
  },
  {
    "slug": "why-stop-now",
    "title": "Why Stop Now?",
    "year": 2022,
    "coverUrl": "https://i.scdn.co/image/ab67616d0000b2733e3ccae2643281ebc19bf95d",
    "spotifyUrl": "https://open.spotify.com/album/4b7W1hQlHccUHfb76VBXf7",
    "appleUrl": null,
    "youtubeUrl": null,
    "bandcampUrl": null
  },
  {
    "slug": "darkness-reigns",
    "title": "Darkness Reigns",
    "year": 2022,
    "coverUrl": "https://i.scdn.co/image/ab67616d0000b273bfe796d752fc629264512421",
    "spotifyUrl": "https://open.spotify.com/album/5BXxV9sPJwIRWGxK6jXJJV",
    "appleUrl": null,
    "youtubeUrl": null,
    "bandcampUrl": null
  },
  {
    "slug": "stateless-ambience-vol-2",
    "title": "Stateless (Ambience Vol. 2)",
    "year": 2022,
    "coverUrl": "https://i.scdn.co/image/ab67616d0000b273bc8f40cb2fb104b4e52d0eaa",
    "spotifyUrl": "https://open.spotify.com/album/25b231vT48Qc53NhSkHQHV",
    "appleUrl": null,
    "youtubeUrl": null,
    "bandcampUrl": null
  },
  {
    "slug": "timeless-ambience-vol-1",
    "title": "Timeless (Ambience, Vol. 1)",
    "year": 2021,
    "coverUrl": "https://i.scdn.co/image/ab67616d0000b27374883106c9e7c4db0e1889ab",
    "spotifyUrl": "https://open.spotify.com/album/3SrKmwS2dAcI14VJMW0DhK",
    "appleUrl": null,
    "youtubeUrl": null,
    "bandcampUrl": null
  },
  {
    "slug": "what-if",
    "title": "What If...?",
    "year": 2021,
    "coverUrl": "https://i.scdn.co/image/ab67616d0000b273bf0b7a756445f7525e666f64",
    "spotifyUrl": "https://open.spotify.com/album/1fOtOZgVL5kUAXH7MOmNAT",
    "appleUrl": null,
    "youtubeUrl": null,
    "bandcampUrl": null
  }
];
